config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'sessions#new'
  resources :tasks

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  namespace :admin do
    get '/dashboard', to: 'users#index'
    get '/toggle/:id', to: 'users#toggle'
    post '/createbyadmin', to: 'users#create_by_admin'
    resources :users, except: [:new, :index]
  end

  get '/search', to: 'tasks#search'
  get '/label/search', to: 'labels#search'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_labels
  has_many :labels, through: :task_labels
  before_validation :add_default_detail

  validates :name, length: { in: 3..90 }
  validates :detail, length: { in: 3..300 }

  $statuses = ['Unstarted', 'In Progress', 'Completed']
  enum priority_type: { Low: 0, Medium: 1, High: 2 }

  scope :search, ->(search_name, search_status) {
    @name_param = search_name.to_s.downcase
    @status_param = search_status.to_s.downcase

    if @name_param.present? && @status_param.blank?
      where("lower(name) LIKE ?", "%#{@name_param}%")

    elsif @status_param.present? && @name_param.blank?
      where("lower(status) LIKE ?", "%#{@status_param}%")

    elsif @name_param.present? && @status_param.present?
      where("lower(name) LIKE ? AND lower(status) LIKE ?",
                                "%#{@name_param}%", "%#{@status_param}%")
    end
  }

  private
  def add_default_detail
    if detail.blank?
      self.detail = 'Default Detail'
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @sort = params[:sort]
    if @sort
      @tasks = current_user.tasks.all.order(@sort).paginate(page: params[:page], per_page: 5)
    else
      @tasks = current_user.tasks.all.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
    end
  end

  def search
    if params[:search_name].present? || params[:search_status].present?
      @results = Task.search(params[:search_name], params[:search_status])
    else
      redirect_to tasks_path
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    if @task.save
      flash[:notice] = "Task Created"
      redirect_to @task
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:notice] = "Edited Successfully"
      redirect_to @task
    else
      render 'edit'
    end
  end

  def destroy
    if @task.destroy
      flash[:notice] = "Deleted Successfully"
      redirect_to tasks_path
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :detail, :expired_at,
      :status, :priority_type, label_ids: [])
  end

  def require_same_user
    if current_user != @task.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own posts"
      redirect_to @task
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task.html.erb
<h1><%= header %></h1>

<%= form_with(model: @task, local: true ) do |form| %>
<% if @task.errors.any? %>
<div id="error_explanation">
  <h2><%= @task.errors.count %> There are errors. </h2>
    <% @task.errors.full_messages.each do |msg| %>
    <%= msg %>
    <% end %>
</div>
<% end %>
<div id="wrapper">
  <div class="task">
    <%= form.label :name %> <br>
    <%= form.text_field :name %>
  </div>
  <div class="task">
    <%= form.label :detail %> <br>
    <%= form.text_area :detail, rows:"4", cols:"25" %>
  </div>
  <div class="task">
    <%= form.label :expired_at %> <br>
    <%= form.datetime_select :expired_at %>
  </div>
  <div class="task">
    <%= form.label :status %> <br>
    <%= form.select :status, $statuses %>
  </div>
  <div class="task">
    <%= form.label :priority_type %> <br>
    <%= form.select :priority_type, Task.priority_types.keys%>
  </div>
  <div class="task">
    <%= form.collection_check_boxes :label_ids, current_user.labels.all, :id, :name do |lb| %>
      <% lb.label {lb.check_box + lb.text } %>
    <% end %>
  </div>
  <div class="submit">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'task', header: "Edit the task" %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>Task List</h1>

  <h2>
  <%= form_tag(search_path, method: "get") do %>
    <%= search_field_tag :search_name, params[:search_name],
      placeholder: "Search by Name" %>
    <%= select_tag :search_status,
        options_for_select(["", "Unstarted", "In Progress", "Completed"]) %>
    <%= button_tag "Search" %>
  <% end %>
  </h2>

  <%= link_to "Sort by creation date",
    sort: "created_at desc" %> |
  <%= link_to "Sort by expiration date",
    sort: "expired_at desc" %> |
  <%= link_to "Sort by priority",
    sort: "priority_type desc" %>
  <div id="task_list">
    <table class="table">
      <tr>
        <th class="left">ID</th>
        <th class="left">Name</th>
        <th class="left">Detail</th>
        <th class="left">Expired at</th>
        <th class="left">Status</th>
        <th class="left">Priority</th>
        <th colspan=3>Actions</th>
      </tr>
      <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.name %></td>
        <td><%= task.detail %></td>
        <td><%= task.expired_at %></td>
        <td><%= task.status %></td>
        <td><%= task.priority_type %></td>
        <td class="action"><%= link_to 'Show', task_path(task) %></td>
        <td class="action"><%= link_to 'Edit', edit_task_path(task) %></td>
        <td class="action"><%= link_to 'Delete', task_path(task),
                            method: :delete,
                            data: {confirm:'Are you sure you want to delete? '} %> </td>
      </tr>
      <% end %>
    </table>
  </div>

  <h3>
    <%= will_paginate @tasks %>
  </h3>
</div>

app/views/tasks/new.html.erb
<%= render 'task', header: "Create a new Task" %>

app/views/tasks/search.html.erb
<h2>Search Results</h2>
<% if @results.count == 0 %>
  <h3>There is no item matched by the search word</h3>
<% else %>
  <div id="task_list">
      <table class="table">
        <tr>
          <th class="left">ID</th>
          <th class="left">Name</th>
          <th class="left">Detail</th>
          <th class="left">Expired at</th>
          <th class="left">Status</th>
          <th class="left">Priority</th>
          <th colspan=3>Actions</th>
        </tr>
      <% @results.each do |result| %>
        <tr>
          <td><%= result.id %></td>
          <td><%= result.name %></td>
          <td><%= result.detail %></td>
          <td><%= result.expired_at %></td>
          <td><%= result.status %></td>
          <td><%= result.priority_type %></td>
          <td class="action"><%= link_to 'Show', task_path(result) %></td>
          <td class="action"><%= link_to 'Edit', edit_task_path(result) %></td>
          <td class="action"><%= link_to 'Delete', task_path(result),
                              method: :delete,
                              data: {confirm:'Are you sure you want to delete? '} %> </td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

<div class="btn"><%= link_to'Return to Task List', tasks_path %></div>

app/views/tasks/show.html.erb
<h1>Showing Task Details</h1>

<p><strong>Name: </strong><%= @task.name %></p>
<p><strong>Detail: </strong><%= @task.detail %></p>
<p><strong>Expired at: </strong><%= @task.expired_at.to_s(:long) %></p>
<p><strong>Status: </strong><%= @task.status %></p>
<p><strong>Priority: </strong><%= @task.priority_type %></p>
<p>
  <% if @task.labels.any? %>
    <strong><em>Labels: </em></strong>
    <% @task.labels.each do |label| %>
      <span class="label"><%= label.name %></span>
    <% end %>
  <% end %>
</p>
<%= link_to 'Home', tasks_path %> |
<%= link_to 'Edit', edit_task_path(@task)%> |
<%= link_to 'Delete', task_path(@task), method: :delete,
    data: { confirm: "Are you sure?" }%>