config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'sessions#new'
  resources :tasks

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  namespace :admin do
    get '/dashboard', to: 'users#index'
    get '/toggle/:id', to: 'users#toggle'
    post '/createbyadmin', to: 'users#create_by_admin'
    resources :users, except: [:new, :index]
  end

  get '/search', to: 'tasks#search'
  get '/label/search', to: 'labels#search'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
  has_many :task_labels
  has_many :tasks, through: :task_labels
  validates :name, length: { in: 2..30 }
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @labels = current_user.labels.all.paginate(page: params[:page], per_page: 5)
  end

  def search
    @label = Label.find(params[:label_id])
    @results = @label.tasks
  end

  def show
  end

  def new
    @label = Label.new
  end

  def edit
  end

  def create
    @label = Label.new(label_params)
    @label.user = current_user
    if @label.save
      flash[:notice] = "Label Created"
      redirect_to @label
    else
      render 'new'
    end
  end

  def update
    if @label.update(label_params)
      flash[:notice] = "Edited Successfully"
      redirect_to @label
    else
      render 'edit'
    end
  end

  def destroy
    if @label.destroy
      flash[:notice] = "Deleted Successfully"
      redirect_to labels_path
    end
  end

  private

  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name)
  end

  def require_same_user
    if current_user != @label.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own labels"
      redirect_to @label
    end
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="wrapper">
    <div class="task">
      <%= form.label :name %> <br>
      <%= form.text_field :name %>
    </div>

    <div class="submit">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<div class="container">

  <h1>Labels List</h1>

  <h2>
    <%= form_with(model: @label, url: "/label/search", method: "get", local: true ) do |form| %>
      <%= form.collection_select(:label_id, current_user.labels.all, :id, :name, { multiple: false }) %>
      <%= form.button "Search" %>
    <% end %>
  </h2>

  <div id="task_list">
    <table class="table">
      <tr>
        <th class="left">Name</th>
        <th colspan=3>Actions</th>
      </tr>
      <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td class="action"><%= link_to 'Show', label_path(label) %></td>
        <td class="action"><%= link_to 'Edit', edit_label_path(label) %></td>
        <td class="action"><%= link_to 'Delete', label_path(label),
                            method: :delete,
                            data: {confirm:'Are you sure you want to delete?'} %> </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

<h3>
  <%= will_paginate @labels %>
</h3>

<div class="btn">
  <%= link_to 'New Label', new_label_path %>
</div>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path %>

app/views/labels/search.html.erb
<h2>Label Search Results</h2>
<% if @results.count == 0 %>
  <h3>There is no item matched by the search word</h3>
<% else %>
  <div id="task_list">
      <table class="table">
        <tr>
          <th class="left">ID</th>
          <th class="left">Name</th>
          <th class="left">Detail</th>
          <th class="left">Expired at</th>
          <th class="left">Status</th>
          <th class="left">Priority</th>
          <th colspan=3>Actions</th>
        </tr>
      <% @results.each do |result| %>
        <tr>
          <td><%= result.id %></td>
          <td><%= result.name %></td>
          <td><%= result.detail %></td>
          <td><%= result.expired_at %></td>
          <td><%= result.status %></td>
          <td><%= result.priority_type %></td>
          <td class="action"><%= link_to 'Show', task_path(result) %></td>
          <td class="action"><%= link_to 'Edit', edit_task_path(result) %></td>
          <td class="action"><%= link_to 'Delete', task_path(result),
                              method: :delete,
                              data: {confirm:'Are you sure you want to delete? '} %> </td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

<div class="btn"><%= link_to'Return to Label List', labels_path %></div>

app/views/labels/show.html.erb
<h1>Showing Label Details</h1>

<p><strong>Name: </strong><%= @label.name %></p>
<%= link_to 'Home', labels_path %> |
<%= link_to 'Edit', edit_label_path(@label)%> |
<%= link_to 'Delete', label_path(@label), method: :delete,
    data: { confirm: "Are you sure?" }%>