config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'sessions#new'
  resources :tasks

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  namespace :admin do
    get '/dashboard', to: 'users#index'
    get '/toggle/:id', to: 'users#toggle'
    post '/createbyadmin', to: 'users#create_by_admin'
    resources :users, except: [:new, :index]
  end

  get '/search', to: 'tasks#search'
  get '/label/search', to: 'labels#search'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:new, :create]
  before_action :require_same_user, only: [:show, :edit, :update, :destroy]

  def index
    if !current_user.admin?
      flash[:alert] = "Admin dashboard can be accessed only by admins"
      redirect_to tasks_path
    else
      @user = User.new
      @admins = User.where(admin: true).order(created_at: :asc).paginate(page: params[:page], per_page: 5)
      @users = User.where(admin: false).order(created_at: :asc).paginate(page: params[:page], per_page: 5)
    end
  end

  def create_by_admin
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "New user created"
      redirect_to admin_dashboard_path
    else
      flash[:notice] = "Fill all fields"
      redirect_to admin_dashboard_path
    end
  end

  def show
    @tasks = @user.tasks.paginate(page: params[:page], per_page: 5)
    @labels = @user.labels.paginate(page: params[:page], per_page: 5)
  end

  def toggle
    @user = User.find(params[:id])
    @user.toggle!(:admin)
    @user.save
    redirect_to admin_dashboard_path
  end

  # def new
  #   @user = User.new
  # end

  def edit
  end

  # def create
  #   @user = User.new(user_params)
  #   @user.admin = true
  #   @user.save
  #   if @user.save
  #     session[:user_id] = @user.id
  #     flash[:notice] = "Welcome #{@user.username}, you have successfully signed up"
  #     redirect_to admin_user_path(@user.id)
  #   else
  #     render 'new'
  #   end
  # end

  def update
    if @user.update(user_params)
      flash[:notice] = "Account information was successfully updated"
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  def destroy
    @admins = User.where(admin: true)
    if @admins.count == 1
      flash[:notice] = "There must be at least one admin user"
      redirect_to admin_dashboard_path
    else
      @user.destroy
      session[:user_id] = nil if @user == current_user
      flash[:notice] = "User account deleted successfully"
      redirect_to admin_dashboard_path
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only check and edit your own account"
      redirect_to tasks_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:new, :create]
  before_action :require_same_user, only: [:show, :edit, :update, :destroy]

  # def index
  #   @users = User.all.order(created_at: :asc).paginate(page: params[:page], per_page: 5)
  # end

  def show
    @tasks = @user.tasks.paginate(page: params[:page], per_page: 5)
    @labels = @user.labels.paginate(page: params[:page], per_page: 5)
  end

  def new
    if logged_in?
      flash[:alert] = "Already Login"
      redirect_to tasks_path
    else
      @user = User.new
    end
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}, you have successfully signed up"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "User account deleted successfully"
    redirect_to admin_dashboard_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only check and edit your own account"
      redirect_to tasks_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_user.html.erb
<h1><%= header %></h1>

<%= form_with(model: @user, url: "/admin/users", method: "post", local: true) do |form| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %> There are errors. </h2>
      <% @user.errors.full_messages.each do |msg| %>
      <%= msg %>
      <% end %><%= form.label :username %>
  </div>
  <% end %>
  <div id="wrapper">
    <div class="task">
      <%= form.label :username %> <br>
      <%= form.text_field :username %>
    </div>
    <div class="task">
      <%= form.label :email %> <br>
      <%= form.email_field :email %>
    </div>
    <div class="task">
      <%= form.label :password %> <br>
      <%= form.password_field :password %>
    </div>
    <div class="task">
      <%= form.label :password_confirmation %> <br>
      <%= form.password_field :password_confirmation %>
    </div>
    <div class="submit">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= render 'user', header: "Edit profile" %>

app/views/admin/users/index.html.erb
<div class="container">
  <h1>Admin Dashboard</h1>

  <h3>
    <%= will_paginate @users %>
  </h3>

  <h3>Admins</h3>
  <div id="task_list">
    <table class="table">
      <tr>
        <th class="left">ID</th>
        <th class="left">Username</th>
        <th class="left">Email</th>
        <th class="left">Tasks</th>
        <th class="left">Labels</th>
        <th colspan=4>Actions</th>
      </tr>
      <% @admins.each do |user| %>
      <tr>
        <% if logged_in? && (user == current_user ||  current_user.admin?) %>
          <td><%= user.id %></td>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
          <td><%= user.tasks.count %></td>
          <td><%= user.labels.count %></td>
          <td class="action"><%= link_to 'MakeUser', admin_path(user) %></td>
          <td class="action"><%= link_to 'Show', admin_user_path(user) %></td>
          <td class="action"><%= link_to 'Edit', edit_admin_user_path(user) %></td>
          <td class="action"><%= link_to 'Delete', admin_user_path(user),
                              method: :delete,
                              data: {confirm:'Are you sure you want to delete? '} %> </td>
        <% end %>
      </tr>
      <% end %>
    </table>
  </div> <br>

  <h3>Users</h3>
  <div id="task_list">
    <table class="table">
      <tr>
        <th class="left">ID</th>
        <th class="left">Username</th>
        <th class="left">Email</th>
        <th class="left">Tasks</th>
        <th class="left">Labels</th>
        <th colspan=4>Actions</th>
      </tr>
      <% @users.each do |user| %>
      <tr>
        <% if logged_in? && (user == current_user ||  current_user.admin?) %>
          <td><%= user.id %></td>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
          <td><%= user.tasks.count %></td>
          <td><%= user.labels.count %></td>
          <td class="action"><%= link_to 'MakeAdmin', admin_path(user) %></td>
          <td class="action"><%= link_to 'Show', user_path(user) %></td>
          <td class="action"><%= link_to 'Edit', edit_user_path(user) %></td>
          <td class="action"><%= link_to 'Delete', user_path(user),
                              method: :delete,
                              data: {confirm:'Are you sure you want to delete? '} %> </td>
        <% end %>
      </tr>
      <% end %>
    </table>
  </div> <br>

  <h3>Create new user</h3>
  <%= form_with(model: @user, url: "/admin/createbyadmin", method: "post", local: true ) do |form| %>
    <div id="wrapper">
      <div class="task">
        <%= form.label :username %> <br>
        <%= form.text_field :username %>
      </div>
      <div class="task">
        <%= form.label :email %> <br>
        <%= form.email_field :email %>
      </div>
      <div class="task">
        <%= form.label :password %> <br>
        <%= form.password_field :password %>
      </div>
      <div class="task">
        <%= form.label :password_confirmation %> <br>
        <%= form.password_field :password_confirmation %>
      </div>
      <div class="submit">
        <%= form.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/users/new.html.erb
<%= render 'user', header: "Create a new Admin Account" %>
<div class="btn"><%= link_to'Have an account, LogIn', root_path %></div>

app/views/admin/users/show.html.erb
<h1>Showing User Details</h1>

<p><strong>Username: </strong><%= @user.username %></p>
<p><strong>Email: </strong><%= @user.email %></p>
<p>
  <% if @user.tasks.count == 1 %>
    <%= "#{@user.tasks.count} task" %>
  <% else %>
    <%= "#{@user.tasks.count} tasks" %>
  <% end %>
</p>
<p>
  <% if @user.labels.count == 1 %>
    <%= "#{@user.labels.count} label" %>
  <% else %>
    <%= "#{@user.labels.count} labels" %>
  <% end %>
</p>
<%= link_to 'Home', tasks_path %> |
<%= link_to 'Edit', edit_admin_user_path(@user)%> |
<%= link_to 'Delete', admin_user_path(@user), method: :delete,
    data: { confirm: "Are you sure?" }%>

<h3>
  <%= will_paginate @tasks %>
</h3>
<% if @tasks.present? %>
  <h2>Tasks</h2>
  <div id="task_list">
    <table class="table">
      <tr>
        <th class="left">ID</th>
        <th class="left">Name</th>
        <th class="left">Detail</th>
        <th class="left">Expired at</th>
        <th class="left">Status</th>
        <th class="left">Priority</th>
        <th colspan=3>Actions</th>
      </tr>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.id %></td>
          <td><%= task.name %></td>
          <td><%= task.detail %></td>
          <td><%= task.expired_at %></td>
          <td><%= task.status %></td>
          <td><%= task.priority_type %></td>
          <td class="action"><%= link_to 'Show', task_path(task) %></td>
          <td class="action"><%= link_to 'Edit', edit_task_path(task) %></td>
          <td class="action"><%= link_to 'Delete', task_path(task),
                              method: :delete,
                              data: {confirm:'Are you sure you want to delete? '} %> </td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

<% if @labels.present? %>
  <h2>Labels</h2>
  <div id="task_list">
    <table class="table">
      <tr>
        <th class="left">Name</th>
        <th colspan=3>Actions</th>
      </tr>
      <% @labels.each do |label| %>
        <tr>
          <td><%= label.name %></td>
          <td class="action"><%= link_to 'Show', label_path(label) %></td>
          <td class="action"><%= link_to 'Edit', edit_label_path(label) %></td>
          <td class="action"><%= link_to 'Delete', label_path(label),
                              method: :delete,
                              data: {confirm:'Are you sure you want to delete? '} %> </td>
        </tr>
      <% end %>
    </table>
  </div> <br> <br>
<% end %>