config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root 'sessions#new'
  resources :tasks

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  namespace :admin do
    get '/dashboard', to: 'users#index'
    get '/toggle/:id', to: 'users#toggle'
    post '/createbyadmin', to: 'users#create_by_admin'
    resources :users, except: [:new, :index]
  end

  get '/search', to: 'tasks#search'
  get '/label/search', to: 'labels#search'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Everyleaf - Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <nav>
        <ul>
          <li id="left">
            <%= "(Admin)" if current_user.admin? %>
          </li>
          <li id="left">
            <a>
              <%= link_to "#{current_user.username}'s Tasks", tasks_path %>
            </a>
          </li>
          <li class="right">
            <a><%= link_to 'LogOut', logout_path,
                method: :delete %></a>
          </li>
          <li class="right">
            <a><%= link_to 'New Task', new_task_path %></a>
          </li>
          <li class="right">
            <a><%= link_to 'Labels', labels_path %></a>
          </li>
          <li class="right">
            <a><%= link_to 'My Profile', user_path(current_user.id) %></a>
          </li>
          <% if current_user.admin? %>
            <li class="right">
              <a><%= link_to 'Dashboard', admin_dashboard_path %></a>
            </li>
          <% end %>
        </ul>
      </nav>
    <% end %>

    <% flash.each do |name, msg| %>
      <div class="message">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>